# Getting Started with R

## Installation

The first thing you need to do to get started with R is to install it
on your computer. R works on pretty much every platform available,
including the widely available Windows, Mac OS X, and Linux
systems. If you want to watch a step-by-step tutorial on how to install
R for Mac or Windows, you can watch these videos:

- [Installing R on Windows](http://youtu.be/Ohnk9hcxf9M)

- [Installing R on the Mac](https://youtu.be/uxuuWXU-7UQ)

There is also an integrated development environment available for R
that is built by RStudio. I really like this IDE---it has a nice
editor with syntax highlighting, there is an R object viewer, and
there are a number of other nice features that are integrated. You can
see how to install RStudio here

- [Installing RStudio](https://youtu.be/bM7Sfz-LADM)

The RStudio IDE is available from [RStudio's web
site](http://rstudio.com).

## Getting started with the R interface

After you install R you will need to launch it and start writing R
code. Before we get to exactly how to write R code, it's useful to get
a sense of how the system is organized. In these two videos I talk
about where to write code and how set your working directory, which
let's R know where to find all of your files.

- [Writing code and setting your working directory on the Mac](https://youtu.be/8xT3hmJQskU)

- [Writing code and setting your working directory on Windows](https://youtu.be/XBcvH1BpIBo)
